import { DesignThemeDefinition, DesignThemeName } from './token-types';

export const designSemanticTokenNames = [
  'surface-page',
  'surface-card',
  'surface-subtle',
  'surface-inverse',
  'border-subtle',
  'border-strong',
  'text-primary',
  'text-muted',
  'text-inverse',
  'text-accent',
  'text-success',
  'text-danger',
  'action-primary-bg',
  'action-primary-fg',
  'action-primary-hover',
  'action-secondary-bg',
  'action-secondary-fg',
  'action-secondary-border',
  'action-secondary-hover',
  'action-ghost-fg',
  'action-ghost-hover',
  'action-danger-bg',
  'action-danger-fg',
  'action-danger-hover',
  'action-disabled-bg',
  'action-disabled-fg',
  'field-bg',
  'field-border',
  'field-border-hover',
  'field-border-focus',
  'field-placeholder',
  'focus-ring',
] as const;

export type DesignSemanticTokenName = (typeof designSemanticTokenNames)[number];

type DesignSemanticTokenMap = Record<DesignSemanticTokenName, string>;

const lightSemanticTokens: DesignSemanticTokenMap = {
  'surface-page': '#f7faf9',
  'surface-card': '#ffffff',
  'surface-subtle': '#eff4f2',
  'surface-inverse': '#0f1d2d',
  'border-subtle': '#d3dce0',
  'border-strong': '#9aa8b0',
  'text-primary': '#16212b',
  'text-muted': '#5d6b74',
  'text-inverse': '#f4f8fb',
  'text-accent': '#196f5b',
  'text-success': '#186649',
  'text-danger': '#a23f3f',
  'action-primary-bg': '#1a7f68',
  'action-primary-fg': '#ffffff',
  'action-primary-hover': '#146554',
  'action-secondary-bg': '#ffffff',
  'action-secondary-fg': '#1b2b36',
  'action-secondary-border': '#b7c4cc',
  'action-secondary-hover': '#edf3f1',
  'action-ghost-fg': '#1d6758',
  'action-ghost-hover': '#e4f0ec',
  'action-danger-bg': '#b94a4a',
  'action-danger-fg': '#ffffff',
  'action-danger-hover': '#943a3a',
  'action-disabled-bg': '#d9e0e3',
  'action-disabled-fg': '#7b8b95',
  'field-bg': '#ffffff',
  'field-border': '#c1ccd3',
  'field-border-hover': '#8d9ca6',
  'field-border-focus': '#1a7f68',
  'field-placeholder': '#80909a',
  'focus-ring': 'rgb(26 127 104 / 0.34)',
};

const darkSemanticTokens: DesignSemanticTokenMap = {
  'surface-page': '#0f1721',
  'surface-card': '#14202d',
  'surface-subtle': '#1c2c3d',
  'surface-inverse': '#f3f7fa',
  'border-subtle': '#2b3d51',
  'border-strong': '#4b6177',
  'text-primary': '#e7f0f6',
  'text-muted': '#9db0be',
  'text-inverse': '#0f1721',
  'text-accent': '#72d5be',
  'text-success': '#8fe3bc',
  'text-danger': '#ffb5b5',
  'action-primary-bg': '#2aa386',
  'action-primary-fg': '#0f1721',
  'action-primary-hover': '#3bc2a2',
  'action-secondary-bg': '#162433',
  'action-secondary-fg': '#d9e6ee',
  'action-secondary-border': '#3e5368',
  'action-secondary-hover': '#223244',
  'action-ghost-fg': '#7bd9c3',
  'action-ghost-hover': '#214239',
  'action-danger-bg': '#d45b5b',
  'action-danger-fg': '#140f0f',
  'action-danger-hover': '#e97272',
  'action-disabled-bg': '#2a3948',
  'action-disabled-fg': '#748596',
  'field-bg': '#132230',
  'field-border': '#35516a',
  'field-border-hover': '#4f6f8b',
  'field-border-focus': '#5cc7ae',
  'field-placeholder': '#88a0b3',
  'focus-ring': 'rgb(92 199 174 / 0.45)',
};

export const designSemanticThemes: Record<
  DesignThemeName,
  DesignThemeDefinition
> = {
  light: {
    colorScheme: 'light',
    semanticTokens: lightSemanticTokens,
  },
  dark: {
    colorScheme: 'dark',
    semanticTokens: darkSemanticTokens,
  },
};
