import { readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const SITE_URL = 'https://angularcleanup.shop';
const NOINDEX_ROUTES = new Set(['/cart', '/checkout', '/book/confirmed']);
const DEFAULT_CHANGEFREQ = 'monthly';
const DEFAULT_PRIORITY = '0.6';

const ROUTE_META = {
  '/': { changefreq: 'weekly', priority: '1.0' },
  '/products': { changefreq: 'weekly', priority: '0.9' },
  '/playbook': { changefreq: 'monthly', priority: '0.8' },
  '/architecture': { changefreq: 'monthly', priority: '0.8' },
  '/faq': { changefreq: 'monthly', priority: '0.8' },
  '/privacy': { changefreq: 'monthly', priority: '0.7' },
  '/book': { changefreq: 'monthly', priority: '0.7' },
};

const currentDirectory = path.dirname(fileURLToPath(import.meta.url));
const workspaceRoot = path.resolve(currentDirectory, '..', '..');
const routesPath = path.join(workspaceRoot, 'apps/shop/src/app/app.routes.ts');
const productsPath = path.join(
  workspaceRoot,
  'apps/shop/public/data/products.json',
);
const outputPath = path.join(workspaceRoot, 'apps/shop/public/sitemap.xml');

const asIsoDate = new Date().toISOString().slice(0, 10);

function escapeXml(value) {
  return value
    .replaceAll('&', '&amp;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;')
    .replaceAll('"', '&quot;')
    .replaceAll("'", '&apos;');
}

function normalizePath(routePath) {
  if (!routePath || routePath === '/') {
    return '/';
  }

  return routePath.startsWith('/') ? routePath : `/${routePath}`;
}

function extractIndexableStaticRoutes(routesSource) {
  const routeMatcher = /path:\s*'([^']*)'/g;
  const orderedRoutes = [];
  const seen = new Set();

  for (const match of routesSource.matchAll(routeMatcher)) {
    const rawPath = match[1];
    const normalizedPath = normalizePath(rawPath);

    if (normalizedPath.includes(':')) {
      continue;
    }

    if (normalizedPath.startsWith('/book/confirmed')) {
      continue;
    }

    if (NOINDEX_ROUTES.has(normalizedPath)) {
      continue;
    }

    if (seen.has(normalizedPath)) {
      continue;
    }

    seen.add(normalizedPath);
    orderedRoutes.push(normalizedPath);
  }

  return orderedRoutes;
}

function extractProductDetailRoutes(productsSource) {
  const products = JSON.parse(productsSource);

  if (!Array.isArray(products)) {
    throw new Error('Expected products.json to contain an array.');
  }

  return products
    .map((product) => product?.slug)
    .filter((slug) => typeof slug === 'string' && slug.length > 0)
    .map((slug) => `/products/${slug}`);
}

function getRouteMeta(route) {
  if (route.startsWith('/products/')) {
    return { changefreq: 'monthly', priority: '0.8' };
  }

  return (
    ROUTE_META[route] ?? {
      changefreq: DEFAULT_CHANGEFREQ,
      priority: DEFAULT_PRIORITY,
    }
  );
}

function buildSitemapXml(routes) {
  const urls = routes.map((route) => {
    const { changefreq, priority } = getRouteMeta(route);
    const loc = `${SITE_URL}${route}`;

    return [
      '  <url>',
      `    <loc>${escapeXml(loc)}</loc>`,
      `    <lastmod>${asIsoDate}</lastmod>`,
      `    <changefreq>${changefreq}</changefreq>`,
      `    <priority>${priority}</priority>`,
      '  </url>',
    ].join('\n');
  });

  return [
    '<?xml version="1.0" encoding="UTF-8"?>',
    '<!-- Generated by tools/seo/generate-sitemap.mjs -->',
    '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">',
    ...urls,
    '</urlset>',
    '',
  ].join('\n');
}

async function main() {
  const [routesSource, productsSource] = await Promise.all([
    readFile(routesPath, 'utf8'),
    readFile(productsPath, 'utf8'),
  ]);

  const staticRoutes = extractIndexableStaticRoutes(routesSource);
  const productRoutes = extractProductDetailRoutes(productsSource);
  const routes = [...staticRoutes];
  const productsIndex = routes.indexOf('/products');

  if (productsIndex >= 0) {
    routes.splice(productsIndex + 1, 0, ...productRoutes);
  } else {
    routes.push(...productRoutes);
  }

  const dedupedRoutes = [...new Set(routes)];
  const sitemapXml = buildSitemapXml(dedupedRoutes);

  await writeFile(outputPath, sitemapXml, 'utf8');
  console.log(
    `Generated sitemap with ${dedupedRoutes.length} routes at ${outputPath}`,
  );
}

main().catch((error) => {
  console.error('Failed to generate sitemap.', error);
  process.exit(1);
});
