import { writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const SITE_URL = 'https://angularcleanup.shop';
const INDEXABLE_ROUTES = [
  '/',
  '/for-managers',
  '/for-technical-leads',
  '/how-it-works',
  '/ai-governance',
  '/privacy',
  '/book',
];
const ROUTE_META = {
  '/': { changefreq: 'weekly', priority: '1.0' },
  '/for-managers': { changefreq: 'weekly', priority: '0.9' },
  '/for-technical-leads': { changefreq: 'weekly', priority: '0.9' },
  '/how-it-works': { changefreq: 'monthly', priority: '0.8' },
  '/ai-governance': { changefreq: 'monthly', priority: '0.8' },
  '/privacy': { changefreq: 'monthly', priority: '0.7' },
  '/book': { changefreq: 'monthly', priority: '0.8' },
};

const currentDirectory = path.dirname(fileURLToPath(import.meta.url));
const workspaceRoot = path.resolve(currentDirectory, '..', '..');
const outputPath = path.join(workspaceRoot, 'apps/shop/public/sitemap.xml');

const asIsoDate = new Date().toISOString().slice(0, 10);

function escapeXml(value) {
  return value
    .replaceAll('&', '&amp;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;')
    .replaceAll('"', '&quot;')
    .replaceAll("'", '&apos;');
}

function buildSitemapXml(routes) {
  const urls = routes.map((route) => {
    const { changefreq, priority } = ROUTE_META[route];
    const loc = `${SITE_URL}${route}`;

    return [
      '  <url>',
      `    <loc>${escapeXml(loc)}</loc>`,
      `    <lastmod>${asIsoDate}</lastmod>`,
      `    <changefreq>${changefreq}</changefreq>`,
      `    <priority>${priority}</priority>`,
      '  </url>',
    ].join('\n');
  });

  return [
    '<?xml version="1.0" encoding="UTF-8"?>',
    '<!-- Generated by tools/seo/generate-sitemap.mjs -->',
    '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">',
    ...urls,
    '</urlset>',
    '',
  ].join('\n');
}

async function main() {
  const sitemapXml = buildSitemapXml(INDEXABLE_ROUTES);
  await writeFile(outputPath, sitemapXml, 'utf8');
  console.log(
    `Generated sitemap with ${INDEXABLE_ROUTES.length} routes at ${outputPath}`,
  );
}

main().catch((error) => {
  console.error('Failed to generate sitemap.', error);
  process.exit(1);
});
